#############################################################################
# Makefile for building: magistrvka
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  magistrvka.pro
# Template: subdirs
# Command: C:\Qt\5.11.2\mingw53_32\bin\qmake.exe -o Makefile magistrvka.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.11.2\mingw53_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.11.2\mingw53_32\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.11.2\mingw53_32\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-DBAccess \
		sub-DBRepSettings \
		sub-DBConnSettingsDialog \
		sub-DiagnosticModel \
		sub-DiagnosticSetting \
		sub-Mainform


sub-DBAccess-qmake_all:  FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd DBAccess\ && $(MAKE) -f Makefile qmake_all
sub-DBAccess: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DBAccess-make_first-ordered: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DBAccess-make_first: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DBAccess-all-ordered: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DBAccess-all: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DBAccess-clean-ordered: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DBAccess-clean: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DBAccess-distclean-ordered: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DBAccess-distclean: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DBAccess-install_subtargets-ordered: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DBAccess-install_subtargets: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DBAccess-uninstall_subtargets-ordered: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DBAccess-uninstall_subtargets: FORCE
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DBRepSettings-qmake_all: sub-DBAccess-qmake_all FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd DBRepSettings\ && $(MAKE) -f Makefile qmake_all
sub-DBRepSettings: FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DBRepSettings-make_first-ordered: sub-DBAccess-make_first-ordered  FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DBRepSettings-make_first: FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DBRepSettings-all-ordered: sub-DBAccess-all-ordered  FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DBRepSettings-all: FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DBRepSettings-clean-ordered: sub-DBAccess-clean-ordered  FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DBRepSettings-clean: FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DBRepSettings-distclean-ordered: sub-DBAccess-distclean-ordered  FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DBRepSettings-distclean: FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DBRepSettings-install_subtargets-ordered: sub-DBAccess-install_subtargets-ordered  FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DBRepSettings-install_subtargets: FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DBRepSettings-uninstall_subtargets-ordered: sub-DBAccess-uninstall_subtargets-ordered  FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DBRepSettings-uninstall_subtargets: FORCE
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DBConnSettingsDialog-qmake_all: sub-DBRepSettings-qmake_all FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd DBConnSettingsDialog\ && $(MAKE) -f Makefile qmake_all
sub-DBConnSettingsDialog: FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DBConnSettingsDialog-make_first-ordered: sub-DBRepSettings-make_first-ordered  FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DBConnSettingsDialog-make_first: FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DBConnSettingsDialog-all-ordered: sub-DBRepSettings-all-ordered  FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DBConnSettingsDialog-all: FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DBConnSettingsDialog-clean-ordered: sub-DBRepSettings-clean-ordered  FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DBConnSettingsDialog-clean: FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DBConnSettingsDialog-distclean-ordered: sub-DBRepSettings-distclean-ordered  FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DBConnSettingsDialog-distclean: FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DBConnSettingsDialog-install_subtargets-ordered: sub-DBRepSettings-install_subtargets-ordered  FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DBConnSettingsDialog-install_subtargets: FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DBConnSettingsDialog-uninstall_subtargets-ordered: sub-DBRepSettings-uninstall_subtargets-ordered  FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DBConnSettingsDialog-uninstall_subtargets: FORCE
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DiagnosticModel-qmake_all: sub-DBConnSettingsDialog-qmake_all FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd DiagnosticModel\ && $(MAKE) -f Makefile qmake_all
sub-DiagnosticModel: FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DiagnosticModel-make_first-ordered: sub-DBConnSettingsDialog-make_first-ordered  FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DiagnosticModel-make_first: FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DiagnosticModel-all-ordered: sub-DBConnSettingsDialog-all-ordered  FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DiagnosticModel-all: FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DiagnosticModel-clean-ordered: sub-DBConnSettingsDialog-clean-ordered  FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DiagnosticModel-clean: FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DiagnosticModel-distclean-ordered: sub-DBConnSettingsDialog-distclean-ordered  FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DiagnosticModel-distclean: FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DiagnosticModel-install_subtargets-ordered: sub-DBConnSettingsDialog-install_subtargets-ordered  FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DiagnosticModel-install_subtargets: FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DiagnosticModel-uninstall_subtargets-ordered: sub-DBConnSettingsDialog-uninstall_subtargets-ordered  FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DiagnosticModel-uninstall_subtargets: FORCE
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DiagnosticSetting-qmake_all: sub-DiagnosticModel-qmake_all FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd DiagnosticSetting\ && $(MAKE) -f Makefile qmake_all
sub-DiagnosticSetting: FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DiagnosticSetting-make_first-ordered: sub-DiagnosticModel-make_first-ordered  FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DiagnosticSetting-make_first: FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DiagnosticSetting-all-ordered: sub-DiagnosticModel-all-ordered  FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DiagnosticSetting-all: FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DiagnosticSetting-clean-ordered: sub-DiagnosticModel-clean-ordered  FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DiagnosticSetting-clean: FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DiagnosticSetting-distclean-ordered: sub-DiagnosticModel-distclean-ordered  FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DiagnosticSetting-distclean: FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DiagnosticSetting-install_subtargets-ordered: sub-DiagnosticModel-install_subtargets-ordered  FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DiagnosticSetting-install_subtargets: FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DiagnosticSetting-uninstall_subtargets-ordered: sub-DiagnosticModel-uninstall_subtargets-ordered  FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DiagnosticSetting-uninstall_subtargets: FORCE
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Mainform-qmake_all: sub-DiagnosticSetting-qmake_all FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd Mainform\ && $(MAKE) -f Makefile qmake_all
sub-Mainform: FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Mainform-make_first-ordered: sub-DiagnosticSetting-make_first-ordered  FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Mainform-make_first: FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Mainform-all-ordered: sub-DiagnosticSetting-all-ordered  FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Mainform-all: FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Mainform-clean-ordered: sub-DiagnosticSetting-clean-ordered  FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Mainform-clean: FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Mainform-distclean-ordered: sub-DiagnosticSetting-distclean-ordered  FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Mainform-distclean: FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Mainform-install_subtargets-ordered: sub-DiagnosticSetting-install_subtargets-ordered  FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Mainform-install_subtargets: FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Mainform-uninstall_subtargets-ordered: sub-DiagnosticSetting-uninstall_subtargets-ordered  FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Mainform-uninstall_subtargets: FORCE
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall

Makefile: magistrvka.pro ../Qt/5.11.2/mingw53_32/mkspecs/win32-g++/qmake.conf ../Qt/5.11.2/mingw53_32/mkspecs/features/spec_pre.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/qdevice.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/features/device_config.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/common/sanitize.conf \
		../Qt/5.11.2/mingw53_32/mkspecs/common/gcc-base.conf \
		../Qt/5.11.2/mingw53_32/mkspecs/common/g++-base.conf \
		../Qt/5.11.2/mingw53_32/mkspecs/common/angle.conf \
		../Qt/5.11.2/mingw53_32/mkspecs/common/windows-vulkan.conf \
		../Qt/5.11.2/mingw53_32/mkspecs/common/g++-win32.conf \
		../Qt/5.11.2/mingw53_32/mkspecs/qconfig.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_charts.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.11.2/mingw53_32/mkspecs/features/qt_functions.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/qt_config.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/win32-g++/qmake.conf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.11.2/mingw53_32/mkspecs/features/exclusive_builds.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/toolchain.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/default_pre.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/win32/default_pre.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/resolve_config.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/default_post.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/resources.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/qtquickcompiler.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/precompile_header.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/warn_on.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/qmake_use.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/file_copies.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/win32/windows.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/testcase_targets.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/exceptions.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/yacc.prf \
		../Qt/5.11.2/mingw53_32/mkspecs/features/lex.prf \
		magistrvka.pro
	$(QMAKE) -o Makefile magistrvka.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
../Qt/5.11.2/mingw53_32/mkspecs/features/spec_pre.prf:
../Qt/5.11.2/mingw53_32/mkspecs/qdevice.pri:
../Qt/5.11.2/mingw53_32/mkspecs/features/device_config.prf:
../Qt/5.11.2/mingw53_32/mkspecs/common/sanitize.conf:
../Qt/5.11.2/mingw53_32/mkspecs/common/gcc-base.conf:
../Qt/5.11.2/mingw53_32/mkspecs/common/g++-base.conf:
../Qt/5.11.2/mingw53_32/mkspecs/common/angle.conf:
../Qt/5.11.2/mingw53_32/mkspecs/common/windows-vulkan.conf:
../Qt/5.11.2/mingw53_32/mkspecs/common/g++-win32.conf:
../Qt/5.11.2/mingw53_32/mkspecs/qconfig.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3danimation.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3danimation_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_charts.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_core.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_edid_support_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_help.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_location.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_network.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioningquick.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_positioningquick_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_remoteobjects.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_repparser.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_repparser_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_script.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.11.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.11.2/mingw53_32/mkspecs/features/qt_functions.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/qt_config.prf:
../Qt/5.11.2/mingw53_32/mkspecs/win32-g++/qmake.conf:
../Qt/5.11.2/mingw53_32/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.11.2/mingw53_32/mkspecs/features/exclusive_builds.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/toolchain.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/default_pre.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/win32/default_pre.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/resolve_config.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/default_post.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/resources.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/qtquickcompiler.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/precompile_header.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/warn_on.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/qmake_use.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/file_copies.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/win32/windows.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/testcase_targets.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/exceptions.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/yacc.prf:
../Qt/5.11.2/mingw53_32/mkspecs/features/lex.prf:
magistrvka.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile magistrvka.pro -spec win32-g++ "CONFIG+=qtquickcompiler"

qmake_all: sub-DBAccess-qmake_all sub-DBRepSettings-qmake_all sub-DBConnSettingsDialog-qmake_all sub-DiagnosticModel-qmake_all sub-DiagnosticSetting-qmake_all sub-Mainform-qmake_all FORCE

make_first: sub-DBAccess-make_first-ordered sub-DBRepSettings-make_first-ordered sub-DBConnSettingsDialog-make_first-ordered sub-DiagnosticModel-make_first-ordered sub-DiagnosticSetting-make_first-ordered sub-Mainform-make_first-ordered  FORCE
all: sub-DBAccess-all-ordered sub-DBRepSettings-all-ordered sub-DBConnSettingsDialog-all-ordered sub-DiagnosticModel-all-ordered sub-DiagnosticSetting-all-ordered sub-Mainform-all-ordered  FORCE
clean: sub-DBAccess-clean-ordered sub-DBRepSettings-clean-ordered sub-DBConnSettingsDialog-clean-ordered sub-DiagnosticModel-clean-ordered sub-DiagnosticSetting-clean-ordered sub-Mainform-clean-ordered  FORCE
distclean: sub-DBAccess-distclean-ordered sub-DBRepSettings-distclean-ordered sub-DBConnSettingsDialog-distclean-ordered sub-DiagnosticModel-distclean-ordered sub-DiagnosticSetting-distclean-ordered sub-Mainform-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-DBAccess-install_subtargets-ordered sub-DBRepSettings-install_subtargets-ordered sub-DBConnSettingsDialog-install_subtargets-ordered sub-DiagnosticModel-install_subtargets-ordered sub-DiagnosticSetting-install_subtargets-ordered sub-Mainform-install_subtargets-ordered FORCE
uninstall_subtargets: sub-DBAccess-uninstall_subtargets-ordered sub-DBRepSettings-uninstall_subtargets-ordered sub-DBConnSettingsDialog-uninstall_subtargets-ordered sub-DiagnosticModel-uninstall_subtargets-ordered sub-DiagnosticSetting-uninstall_subtargets-ordered sub-Mainform-uninstall_subtargets-ordered FORCE

sub-DBAccess-debug_ordered:
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-DBRepSettings-debug_ordered: sub-DBAccess-debug_ordered 
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-DBConnSettingsDialog-debug_ordered: sub-DBRepSettings-debug_ordered 
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-DiagnosticModel-debug_ordered: sub-DBConnSettingsDialog-debug_ordered 
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-DiagnosticSetting-debug_ordered: sub-DiagnosticModel-debug_ordered 
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-Mainform-debug_ordered: sub-DiagnosticSetting-debug_ordered 
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
debug: sub-DBAccess-debug_ordered sub-DBRepSettings-debug_ordered sub-DBConnSettingsDialog-debug_ordered sub-DiagnosticModel-debug_ordered sub-DiagnosticSetting-debug_ordered sub-Mainform-debug_ordered

sub-DBAccess-release_ordered:
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-DBRepSettings-release_ordered: sub-DBAccess-release_ordered 
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-DBConnSettingsDialog-release_ordered: sub-DBRepSettings-release_ordered 
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-DiagnosticModel-release_ordered: sub-DBConnSettingsDialog-release_ordered 
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-DiagnosticSetting-release_ordered: sub-DiagnosticModel-release_ordered 
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-Mainform-release_ordered: sub-DiagnosticSetting-release_ordered 
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
release: sub-DBAccess-release_ordered sub-DBRepSettings-release_ordered sub-DBConnSettingsDialog-release_ordered sub-DiagnosticModel-release_ordered sub-DiagnosticSetting-release_ordered sub-Mainform-release_ordered

sub-DBAccess-check_ordered:
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-DBRepSettings-check_ordered: sub-DBAccess-check_ordered 
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-DBConnSettingsDialog-check_ordered: sub-DBRepSettings-check_ordered 
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-DiagnosticModel-check_ordered: sub-DBConnSettingsDialog-check_ordered 
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-DiagnosticSetting-check_ordered: sub-DiagnosticModel-check_ordered 
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-Mainform-check_ordered: sub-DiagnosticSetting-check_ordered 
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
check: sub-DBAccess-check_ordered sub-DBRepSettings-check_ordered sub-DBConnSettingsDialog-check_ordered sub-DiagnosticModel-check_ordered sub-DiagnosticSetting-check_ordered sub-Mainform-check_ordered

sub-DBAccess-benchmark_ordered:
	@if not exist DBAccess\ mkdir DBAccess\ & if not exist DBAccess\ exit 1
	cd DBAccess\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBAccess\DBAccess.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-DBRepSettings-benchmark_ordered: sub-DBAccess-benchmark_ordered 
	@if not exist DBRepSettings\ mkdir DBRepSettings\ & if not exist DBRepSettings\ exit 1
	cd DBRepSettings\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBRepSettings\DBRepSettings.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-DBConnSettingsDialog-benchmark_ordered: sub-DBRepSettings-benchmark_ordered 
	@if not exist DBConnSettingsDialog\ mkdir DBConnSettingsDialog\ & if not exist DBConnSettingsDialog\ exit 1
	cd DBConnSettingsDialog\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DBConnSettingsDialog\DBConnSettingsDialog.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-DiagnosticModel-benchmark_ordered: sub-DBConnSettingsDialog-benchmark_ordered 
	@if not exist DiagnosticModel\ mkdir DiagnosticModel\ & if not exist DiagnosticModel\ exit 1
	cd DiagnosticModel\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticModel\DiagnosticModel.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-DiagnosticSetting-benchmark_ordered: sub-DiagnosticModel-benchmark_ordered 
	@if not exist DiagnosticSetting\ mkdir DiagnosticSetting\ & if not exist DiagnosticSetting\ exit 1
	cd DiagnosticSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\DiagnosticSetting\DiagnosticSetting.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-Mainform-benchmark_ordered: sub-DiagnosticSetting-benchmark_ordered 
	@if not exist Mainform\ mkdir Mainform\ & if not exist Mainform\ exit 1
	cd Mainform\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\MagistrVka\Mainform\Mainform.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-DBAccess-benchmark_ordered sub-DBRepSettings-benchmark_ordered sub-DBConnSettingsDialog-benchmark_ordered sub-DiagnosticModel-benchmark_ordered sub-DiagnosticSetting-benchmark_ordered sub-Mainform-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

